name: 🔬 Feature Request
description: Propose new feature suggestions or optimizations for existing features
title: "[Request] "
labels: ["enhancement", "Feature Discussion"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem/Pain Point Description
      description: Why can the current design not meet the needs? Is it related to specific scenarios?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the envisioned solution or optimization direction
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other implementation methods?
      placeholder: E.g., Implementation via extended plugins vs. modifying core code
    validations:
      required: false
  - type: textarea
    id: value
    attributes:
      label: Expected Value
      description: Which user groups will benefit from this feature? How will it improve the experience?
    validations:
      required: true
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Intent
      options:
        - label: "I am willing to participate in the development or testing of this feature"
          required: false